
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 270)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.min_speed_value = QtWidgets.QSpinBox(self.centralwidget)
        self.min_speed_value.setGeometry(QtCore.QRect(280, 50, 51, 22))
        self.min_speed_value.setObjectName("min_speed_value")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 211, 21))
        self.label.setObjectName("label")
        self.max_speed_value = QtWidgets.QSpinBox(self.centralwidget)
        self.max_speed_value.setGeometry(QtCore.QRect(280, 90, 51, 22))
        self.max_speed_value.setObjectName("max_speed_value")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 201, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(6, 213, 431, 20))
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setGeometry(QtCore.QRect(104, 172, 181, 21))
        self.apply_button.setObjectName("apply_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 191, 21))
        self.label_3.setObjectName("label_3")
        self.bot_level = QtWidgets.QSpinBox(self.centralwidget)
        self.bot_level.setGeometry(QtCore.QRect(280, 130, 51, 21))
        self.bot_level.setObjectName("bot_level")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Минимальная скорость шарика по оси:"))
        self.label_2.setText(_translate("MainWindow", "Максимальная скорость шарика по оси:"))
        self.label_4.setText(_translate("MainWindow", "Вводить только положительные значения:"))
        self.apply_button.setText(_translate("MainWindow", "Применить значения"))
        self.label_3.setText(_translate("MainWindow", "Сложность бота 0-10(если есть):"))
